### ISSUE TITLE
The app should install anywhere

### ISSUE THREAD

**Issue by noraj1337** [mitre-cyber-academy/registration-app#118]
The app should install anywhere not only on AWS.

See related issue https://github.com/mitre-cyber-academy/registration-app/issues/116 and installation steps https://github.com/mitre-cyber-academy/registration-app/wiki/Installation

**Comment by rbclark** [comment]
What happened here is that we added a feature to sync our VPN certificates used for our competition with an AWS bucket, however we did not gracefully add a fallback when no AWS credentials are available. We will work to add a way to have it fail gracefully ASAP.

**Comment by rbclark** [comment]
Go ahead and give it a try now with the latest master, it should now be fixed.

**Comment by noraj1337** [comment]
@rbclark thx PR worked
