### ISSUE TITLE
Default admin account changed

### ISSUE THREAD

**Issue by noraj1337** [mitre-cyber-academy/registration-app#120]
After doing `bundle exec rake db:seed` two user are created:

+ root@root.com
+ ctf@mitre.org

I guess those are the admin account for  database 'registration_development' and database 'registration_test'.

But what are their password ?

Before this was rbclark@mitre.org / changeme and there was a /admin page. see https://github.com/mitre-cyber-academy/registration-app/issues/47

**Comment by noraj1337** [comment]
PS : this is why https://github.com/mitre-cyber-academy/registration-app/issues/117 is needed

**Comment by rbclark** [comment]
The admin page is still at the same location however it automatically redirects to the main page whenever the user is not logged in as an admin. The new credentials are as follows:

root@root.com - ChangeMe123
ctf@mitre.org - Test123456

I agree the README is in need of an update and we will get to it, unfortunately we have been absolutely slammed with other issues and have not gotten to it yet, I do apologise and we will make sure to do it as soon as we have a chance.

**Comment by noraj1337** [comment]
@rbclark Thanks. Yes I understand, plus you were busy with STEM CTF.
That's why I'm helping with the wiki 😃 

PS : I updated the installation page https://github.com/mitre-cyber-academy/registration-app/wiki/Installation
