### ISSUE TITLE
Add data disclaimer

### ISSUE THREAD

**Issue by Bialogs** [mitre-cyber-academy/registration-app#15]
Add a statement of data protection to the user registration page & profile page

**Comment by rbclark** [comment]
So this already exists now more or less in our mouseover text, and I don't think we're gonna do much better than that. Gonna mark this one ask closed as well.
<img width="233" alt="screen shot 2016-06-22 at 7 31 54 pm" src="https://cloud.githubusercontent.com/assets/2308869/16287283/ff585f5a-38af-11e6-8ef7-4066424d5951.png">
