### ISSUE TITLE
Users are confused that they have to sign up for a team after registering

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/registration-app#35]
We have had multiple users who stated they signed up for the competition but did not receive team credentials, mainly because they never actually registered a team. We need to make this more clear.

**Comment by rbclark** [comment]
https://github.com/mitre-cyber-academy/registration-app/milestone/1 would take care of this by making it possible to make this clear to the user post the start of the CTF and still allowing them to register a team.

**Comment by noraj1337** [comment]
You may want to include the "team joining" step at registration.

While registering the player should be able to either create a team or to join one. So the user is necessary in a team at the end of the registration.

**Comment by rbclark** [comment]
The current fix we are working on for this is merging the scoreboard + registration applications. If scoreboard + registration are one application then users will be able to register even after the competition has started and it will not be a problem. We can then provide single player users with a message when they go to the gameboard that says "you must join or create a team in order to compete". I worry about forcing a team on a user during the registration process since some users sign up before their team captain has created their team.

**Comment by noraj1337** [comment]
@rbclark Yeah, you're right. The merge of the two apps seems unavoidable.
