### ISSUE TITLE
Integrate the scoreboard into the registration site

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/registration-app#37]
It would make things a lot cleaner if we had just one application instead of two. This would probably be best done by migrating all of the scoreboard code into the registration site.

**Comment by Bialogs** [comment]
- [ ] Messages

- [ ] Score adjustments

- [ ] Challenge state

- [ ] Categories

- [ ] Achievements

- [ ] Tests

- [ ] solved challenges

- [ ] submitted flags

- [ ] divisions

- [ ] challenge
