### ISSUE TITLE
User is able to send password reset email when they have never set a password before.

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/registration-app#4]
There is a bit of an edge case that happens if a user registers and then uses the forgot password option before completing registration. It sends them an email asking them to reset their password but then won't let them reset their password because they haven't set their name and a bunch of other fields. In order to get around this we need to do some checking before sending the forgot password email.

**Comment by Bialogs** [comment]
This will be closed when the fix registration issues branch is moved in. Fixed by a devise upgrade.
