### ISSUE TITLE
Top teams should automatically be emailed asking for resumes

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/registration-app#41]
We should automate the requesting of resumes and transcripts and integrate it into the scoreboard for the top 10 teams for each division. We could also put a countdown on it for when it is due by in order to make it clear to the competitors how soon we need the information by. This makes it a lot easier to keep track of the data.

**Comment by Bialogs** [comment]
I'm kind of against a countdown....it's pretty in-your-face.
