### ISSUE TITLE
Installation steps needed

### ISSUE THREAD

**Issue by noraj1337** [mitre-cyber-academy/registration-app#47]
I'm not a dev and I'm not expert on how RoR works.

Can you provide simple steps to configure the app before starting the web server?

Because if I only do:
+ `gem install bundler`
+ `bundle install`
+ `bin/rails server`

I have an error `ActiveRecord::NoDatabaseError (FATAL:  database "registration_development" does not exist` so I assume there is some database provision and configuration (`bundle exec rake something`) to do before starting the web server.

**Comment by rbclark** [comment]
The steps for this application should be pretty much identical to the scoreboard instructions you built yesterday for the scoreboard application.

1. Install ruby.
2. In your terminal run `gem install bundle`
3. Run `bundle install`
4. Install postgres to your system (and create a role with your system username)
5. Run `bundle exec rake db:create`
6. Run `bundle exec rake db:schema:load`
6. Run `bundle exec rake db:seed`
7. Run `bundle exec rails s`
8. Open the webpage shown in your terminal from the last command in your browser.
9. Login to the registration app `http://localhost:3000/admin` as email: `rbclark@mitre.org`, password: `changeme` and change the password.

**Comment by noraj1337** [comment]
OK, I'm not making a PR to include these steps in the README as you are currently working on merging the two apps.
