### ISSUE TITLE
Attempting to join a team with no team captain fails

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/registration-app#51]
Currently if you create a bunch of empty teams in the database with no team captain and then try to join one of them an error is thrown. We should make sure this doesn't happen.

One good thing we could do that would make this easier to fix is adding a users_count field to the database and setting up a counter cache, see http://stackoverflow.com/a/9209705

This would also be useful for fixing the following from happening on the join_team page

<img width="664" alt="screen shot 2017-05-21 at 11 20 04 am" src="https://cloud.githubusercontent.com/assets/2308869/26285129/7a0365b6-3e17-11e7-8df4-18d603c95c63.png">

We could then just set the default team filter to not show teams where the user count is empty, which would hide any team that accidentally gets in that state from the user.

**Comment by James-Tobin** [comment]
@rbclark should we also not display full teams?

**Comment by rbclark** [comment]
@James-Tobin We should still display teams that are full since teams that are full could have spots open up and the pending request doesn't really hurt anything.
