### ISSUE TITLE
Lock team captains from changing the team division once the game is in progress

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/registration-app#55]
The division should not be change-able for ANY team during the competition. This is left over from the scoreboard merge.

**Comment by James-Tobin** [comment]
@rbclark Teams can still be created during the competition right?

**Comment by rbclark** [comment]
Actually we need to discuss if this is needed at all, this may be unnecessary since we really only care about top 10, but yes teams can be created during

**Comment by Bialogs** [comment]
Yes, still needed. Scenario where 2nd place high school team is doing better than 1st college... competition is coming to a close and then high school team switches to college (still eligible for prizes) and then bumps the college team from 1 to 2.

**Comment by rbclark** [comment]
@Bialogs what you have described can't happen since the top 10 teams are locked from changing their division.

**Comment by Bialogs** [comment]
🤦‍♂️ yea....
