### ISSUE TITLE
Team ineligible for prizes when all users are eligible

### ISSUE THREAD

**Issue by James-Tobin** [mitre-cyber-academy/registration-app#60]
When ineligible user leaves team, eligibility doesn't get updated.

To reproduce:

Create two users, Eligible and Ineligible.
Have Eligible create a team.
Have Ineligible join the team.
Team should now be considered NOT eligible for prizes.
Have Ineligible leave the team.
Team is still considered NOT eligible even though the only team member is eligible.

**Comment by rbclark** [comment]
@James-Tobin is this fixed by #57?

**Comment by James-Tobin** [comment]
@rbclark no.

**Comment by rbclark** [comment]
@James-Tobin :(

**Comment by James-Tobin** [comment]
Issue resolved in #65
