### ISSUE TITLE
User requests

### ISSUE THREAD

**Issue by James-Tobin** [mitre-cyber-academy/registration-app#63]
When denying User Join Team Requests as Team Captain, requests don't actually get deleted.  Happens when team is full and when team has open spots.

**Comment by rbclark** [comment]
This is partially solved in 7af20c3 however I need to see if it still reproduces when the team is full.

**Comment by rbclark** [comment]
@James-Tobin is this resolved?

**Comment by James-Tobin** [comment]
@rbclark I am currently testing it, but it seems to be so far.

**Comment by James-Tobin** [comment]
#60 resolves this issue.  Tested for teams that are full, and teams that have open spots.
