### ISSUE TITLE
Remove Devise Security Extension

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/registration-app#68]
It pains me (not really) to have to remove this gem. It provides some small password related changes, all of which we should be able to rip out. The reason for ripping it out is there are 2 open issues that are currently blocking us, 1st of which is rails 5.1 support and 2nd is ruby 2.4 support. The gem also seems basically abandoned.

**Comment by Bialogs** [comment]
We might be able to upgrade to this https://github.com/devise-security/devise-security

**Comment by rbclark** [comment]
The only reason I support adding devise-security in is for captcha support on signup.
